apiVersion: v1
data:
  alertmanager.yml: |
    global: 
      smtp_smarthost: 'smtp.vodafone.de:587'
      smtp_from: 'ksrini_mba@vodafone.de'
      smtp_auth_username: 'ksrini_mba@vodafone.de'
      smtp_auth_password: 'Kambh12#'
    receivers:
    - name: opsmx_alert_receivers
      email_configs:
      - to: no-reply-demo@opsmx.io
        send_resolved: true
        text: " \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        title: '{{.CommonAnnotations.summary}}'
        text: '{{ .CommonAnnotations.description }}'
        #title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        #text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        #text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
    - name: opsmx_email_only
      email_configs:
      - to: no-reply-demo@opsmx.io
        send_resolved: true
        text: " \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
    route:
      group_interval: 5m # Changed from 5m
      group_wait: 10s
      repeat_interval: 2h # Was set to 3h, changed for testing
      receiver: opsmx_alert_receivers
      routes:
      - match: 
          severity: warning
        receiver: opsmx_alert_receivers
        #receiver: opsmx_email_only
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-26T10:00:49Z"
  labels:
    app: prometheus
    chart: prometheus-11.16.2
    component: alertmanager
    heritage: Helm
    release: prom
  name: prom-prometheus-alertmanager
  namespace: oes
  resourceVersion: "26027669"
  selfLink: /api/v1/namespaces/oes/configmaps/prom-prometheus-alertmanager
  uid: bfa11a4c-a858-482a-a861-e1896d6b1feb
