apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-18T08:28:44Z"
  labels:
    app: prometheus
    chart: prometheus-10.4.0
    component: alertmanager
    heritage: Helm
    release: prometheus-1582014510
  name: prometheus-1582014510-alertmanager
  namespace: srini
  resourceVersion: "624028"
  selfLink: /api/v1/namespaces/srini/configmaps/prometheus-1582014510-alertmanager
  uid: ad4328bf-5228-11ea-862b-76258b12429b
