apiVersion: v1
data:
  alerting_rules.yml: |
    groups:
    - name: spinnaker-services-is-down
      rules:
      - alert: spin-is-down
        expr: absent(up{job="opsmx_spinnaker_metrics"}) == 1  
        labels:
          severity: critical
        annotations:
          description: "{{ $labels.service }} appears to be down for more 1 min {{ $value }})"
          summary: One or more Spinnaker services are down 
    - name: gate-latency-too-high
      rules:
      - alert: gate-invocations-increasing-too-fast
        expr: sum (rate(gate:controller:invocations__percentile_total[2m])) > 0.95
        labels:
          severity: warning
        annotations:
          description: "{{ $labels.instance }} invocation latency too high {{ $value }}) > 0.35"
          summary: gate-invocations-increasing-too-fast
    - name: clouddriver-latency-too-high
      rules:
      - alert: clouddriver-latency-too-high
        expr: sum(rate(clouddriver:executionTime__totalTime_total[5m])) by (instance) / sum(rate(clouddriver:executionTime__count_total[5m])) by (instance) > 70000000000
        labels:
          severity: severe
        annotations:
          description: "{{ $labels.instance }} invocation latency too high {{ $value }}) > 700000000"
          summary: Cloud Driver responding too slowly
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 5s
      scrape_timeout: 2s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: opsmx_spinnaker_metrics
      honor_labels: true
      metrics_path: /prometheus_metrics
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - spin-srini
      relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_service_label_app
          regex: spin
        - action: keep
          source_labels:
          - __meta_kubernetes_pod_container_port_number
          regex: "8008"
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Node;(.*)
          replacement: ${1}
          target_label: node
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Pod;(.*)
          replacement: ${1}
          target_label: pod
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - target_label: endpoint
          replacement: "8008"
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: srini
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: prometheus
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
          regex: .*
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop
  recording_rules.yml: |
    {}
  rules: |
    {}
## STUFF that can be added to the bottom of the relable_configs for selecting one or two lables
#        - source_labels: [ __name__ ]
#          regex: '(clouddriver:redis:command:invocation:pipelined_total|clouddriver:cats:redisCache:evict:itemCount_total)'
#          action: keep

## Stuff that can be added to limit to a specific service-name(s) from k8s
#        - source_labels:
#          - __meta_kubernetes_service_name
#          target_label: job
#          regex: spin-clouddriver
#          action: keep

kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-10.4.0
    component: server
    heritage: Helm
    release: prometheus-1582014510
  name: prometheus-1582014510-server
  namespace: srini
