apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    chart: prometheus-10.4.0
    component: server
    heritage: Helm
    release: prometheus-1584018984
  name: prometheus-1584018984-server
  namespace: srini
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
