{
 "title": "Opsmx OES",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "oes-sapor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "sapor JVM heap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"heap\",component=\"sapor\"}"
      }
     ]
    },
    {
     "title": "sapor CPU used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app=\"oes\",component=\"sapor\"}"
      }
     ]
    },
    {
     "title": "sapor JVM nonheap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"nonheap\",component=\"sapor\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "oes-platform",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "platform JVM heap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"heap\",component=\"platform\"}\n"
      }
     ]
    },
    {
     "title": "platform CPU used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app=\"oes\",component=\"platform\"}"
      }
     ]
    },
    {
     "title": "platform JVM nonheap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"nonheap\",component=\"platform\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "oes-gate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "gate Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{container=\"oes-gate\"}"
      }
     ]
    },
    {
     "title": "gate CPU used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"oes-gate\"}[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "oes-visibility",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "visibility JVM heap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"heap\",component=\"visibility\"}"
      }
     ]
    },
    {
     "title": "visibility cpu usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app=\"oes\",component=\"visibility\"}"
      }
     ]
    },
    {
     "title": "visibility JVM nonheap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\",component=\"visibility\"}"
      }
     ]
    }
   ]
  },
  { "title": "oes-dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "dashboard JVM heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"heap\",component=\"dashboard\"}"
    }
   ]
  },
  {
   "title": "dashboard CPU used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{app=\"oes\",component=\"dashboard\"}"
    }
   ]
  },
  {
   "title": "dashboard JVM nonheap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",component=\"visibility\"}"
    }
   ]
  },
  {
   "title": "oes-autopilot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "autopilot JVM heap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"heap\",component=\"autopilot\"}\n"
      }
     ]
    },
    {
     "title": "autopilot CPU used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app=\"oes\",component=\"autopilot\"}"
      }
     ]
    },
    {
     "title": "autopilot JVM nonheap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"oes\",area=\"nonheap\",component=\"autopilot\"}"
      }
     ]
    }
   ]
  }
 ]
}