{
 "title": "Spinnaker Microservices",
 "description": "All-in-one dashboard for Spinnaker's microservices",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Function", "label": "Function", "query": "delta,rate,idelta,irate" },
   { "name": "SamplePeriod", "label": "SamplePeriod", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "clouddriver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "clouddriver_caching pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-clouddriver-caching-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-caching-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-caching-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "clouddriver_caching controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "In promotheus but no data",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(clouddriver_caching:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(clouddriver_caching:controller:invocations__count_total [$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "clouddriver_caching controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in promotheus but no data",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(clouddriver_caching:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "clouddriver_caching memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "clouddriver_caching:jvm:memory:used__value",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "clouddriver_caching controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in promotheus but no data",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 7 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_caching:controller:invocations__total[$SamplePeriod])) / sum(rate(clouddriver_caching:controller:invocations__count_total [$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "clouddriver_caching 5XX percentage",
     "type": "graph",
     "description": "getting data when we  use status has 2xx in metric ",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_caching:controller:invocations__count_total{status=\"5xx\"})/sum(clouddriver_caching:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_caching 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_caching:controller:invocations__count_total{status=\"2xx\"})/sum(clouddriver_caching:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_rw pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-clouddriver-rw-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-rw-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-rw-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "clouddriver_rw controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in promotheus but no data",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(clouddriver_rw:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(clouddriver_rw:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "clouddriver_rw controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in promotheus but no data",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 13 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(clouddriver_rw:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "clouddriver_caching memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "clouddriver_rw:jvm:memory:used__value",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "clouddriver_rw controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in promotheus but no data",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 19 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_rw:controller:invocations__total[$SamplePeriod])) / sum(rate(clouddriver_rw:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "clouddriver_rw 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_rw:controller:invocations__count_total{status=\"5xx\"})/sum(clouddriver_rw:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_rw 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_rw:controller:invocations__count_total{status=\"2xx\"})/sum(clouddriver_rw:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_ro pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "clouddriver_ro controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in [prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 25 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(clouddriver_ro:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(clouddriver_ro:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "clouddriver_ro controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(clouddriver_ro:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "clouddriver_ro memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "clouddriver_ro:jvm:memory:used__value",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "clouddriver_ro controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 32 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_ro:controller:invocations__total[$SamplePeriod])) / sum(rate(clouddriver_ro:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "clouddriver_ro 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_ro:controller:invocations__count_total{status=\"5xx\"})/sum(clouddriver_ro:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_ro 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_ro:controller:invocations__count_total{status=\"2xx\"})/sum(clouddriver_ro:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-deck-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-deck-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-clouddriver-ro-deck-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_ro_deck:controller:invocations__total[$SamplePeriod])) / sum(rate(clouddriver_ro_deck:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(clouddriver_ro_deck:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "clouddriver_ro_deck:jvm:memory:used__value",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 45 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(clouddriver_ro_deck:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(clouddriver_ro_deck:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_ro_deck:controller:invocations__count_total{status=\"5xx\"})/sum(clouddriver_ro_deck:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "clouddriver_ro_deck 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(clouddriver_ro_deck:controller:invocations__count_total{status=\"2xx\"})/sum(clouddriver_ro_deck:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Kubernetes success API calls [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 10, "w": 20, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_caching:kubernetes:api__count_total{success=\"true\"}[$SamplePeriod])) by (account, namespace, action)",
       "legendFormat": "{{account}} / {{ namespace}} / {{ action }}"
      }
     ]
    },
    {
     "title": "Kubernetes success latency API calls [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_caching:kubernetes:api__total{success=\"true\"}[$SamplePeriod])) by (account, namespace, action) / sum(rate(clouddriver_caching:kubernetes:api__count_total{success=\"true\"}[$SamplePeriod])) by (account, namespace, action)",
       "legendFormat": "{{account}} / {{ namespace}} / {{ action }}"
      }
     ]
    },
    {
     "title": "Kubernetes failed API calls [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_caching:kubernetes:api__count_total{success!=\"true\"}[$SamplePeriod])) by (account, namespace, action)",
       "legendFormat": "{{account}} / {{ namespace}} / {{ action }}"
      }
     ]
    },
    {
     "title": "Kubernetes failure latency API calls [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(clouddriver_caching:kubernetes:api__total{success!=\"true\"}[$SamplePeriod])) by (account, namespace, action) / sum(rate(clouddriver_caching:kubernetes:api__count_total{success!=\"true\"}[$SamplePeriod])) by (account, namespace, action)",
       "legendFormat": "{{account}} / {{ namespace}} / {{ action }}"
      }
     ]
    }
   ]
  },
  {
   "title": "orca",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "orca pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-orca-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-orca-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-orca-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "orca controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(orca:controller:invocations__total[$SamplePeriod])) / sum(rate(orca:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "orca controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(orca:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "orca memory used",
     "type": "graph",
     "description": "added __value",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "orca:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "orca controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(orca:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(orca:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "orca 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(orca:controller:invocations__count_total{status=\"5xx\"})/sum(orca:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "orca 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(orca:controller:invocations__count_total{status=\"2xx\"})/sum(orca:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "orca queue depth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "orca:queue:depth__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "orca queue orphaned messages active",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(orca:queue:orphaned:messages__value)",
       "legendFormat": "orphaned"
      }
     ]
    },
    {
     "title": "orca number of exections",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(orca:executions:active__value != 0)"
      }
     ]
    },
    {
     "title": "orca queue unacked messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(orca:queue:unacked:depth__value) by (pod, application)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "orca active threads",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(orca:threadpool:activeCount__value) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "orca blocked queues",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(orca:threadpool:blockingQueueSize__value) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "orca queue pushed messages total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(orca:queue:pushed:messages__count_total) by (pod, application)",
       "legendFormat": "{{ application }} / {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "gate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "gate pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-gate-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-gate-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-gate-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "gate controller latency [${SamplePeriod}]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gate:controller:invocations__total[$SamplePeriod])) / sum(rate(gate:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "gate controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(gate:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "gate memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "gate:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "gate controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(gate:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(gate:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "gate 5XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(gate:controller:invocations__count_total{status=\"5xx\"})/sum(gate:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "gate 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(gate:controller:invocations__count_total{status=\"2xx\"})/sum(gate:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "gate hystrix countShortCircuited",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gate:hystrix:countShortCircuited)",
       "legendFormat": "countShortCircuited"
      }
     ]
    },
    {
     "title": "gate hystrix countExceptionsThrown",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gate:hystrix:countExceptionsThrown)",
       "legendFormat": "countExceptionsThrown"
      }
     ]
    },
    {
     "title": "gate hystrix rollingCountFailure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gate:hystrix:rollingCountFailure)",
       "legendFormat": "rollingCountFailure"
      }
     ]
    },
    {
     "title": "gate unknown okhttp percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " 100*sum(gate:okhttp:requests__count_total{status=\"Unknown\",success=\"false\"})/sum(gate:okhttp:requests__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "gate 2XX okhttp percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(gate:okhttp:requests__count_total{status=\"2xx\",success=\"true\"})/sum(gate:okhttp:requests__count_total)",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  },
  {
   "title": "igor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "igor pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-igor-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-igor-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-igor-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "igor controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(igor:controller:invocations__total[$SamplePeriod])) / sum(rate(igor:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "igor controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(igor:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "igor memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "igor:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "igor controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(igor:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(igor:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "igor 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(igor:controller:invocations__count_total{status=\"5xx\"})/sum(igor:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "igor 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(igor:controller:invocations__count_total{status=\"2xx\"})/sum(igor:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "igor unknown okhttp percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(igor:okhttp:requests__count_total{status=\"Unknown\",success=\"false\"})/sum(igor:okhttp:requests__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "igor 2XX okhttp percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(igor:okhttp:requests__count_total{status=\"2xx\",success=\"true\"})/sum(igor:okhttp:requests__count_total)",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  },
  { "title": "fiat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "fiat pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{pod=~\"spin-fiat-.*\"} == 1)",
     "legendFormat": "pods up"
    },
    {
     "expr": "count(up{pod=~\"spin-fiat-.*\"} == 0) OR on() vector(0)",
     "legendFormat": "pods down"
    },
    {
     "expr": "count(up{pod=~\"spin-fiat-.*\"})",
     "legendFormat": "total pods"
    }
   ]
  },
  {
   "title": "fiat controller latency [${SamplePeriod}]",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fiat:controller:invocations__total[$SamplePeriod])) / sum(rate(fiat:controller:invocations__count_total[$SamplePeriod]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "fiat controller invocations by method [${SamplePeriod}]",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": " label_replace(sum(rate(fiat:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "{{ controller }} / {{ method }}"
    }
   ]
  },
  {
   "title": "fiat memory used",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "fiat:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "fiat controller invocation latency by method [${SamplePeriod}]",
   "type": "graph",
   "description": "not in prom",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(fiat:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(fiat:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "fiat 5XX percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*sum(fiat:controller:invocations__count_total{status=\"5xx\"})/sum(fiat:controller:invocations__count_total)",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "fiat 2XX percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*sum(fiat:controller:invocations__count_total{status=\"2xx\"})/sum(fiat:controller:invocations__count_total)",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "fiat hystrix countShortCircuited",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fiat:hystrix:countShortCircuited)",
     "legendFormat": "countShortCircuited"
    }
   ]
  },
  {
   "title": "fiat hystrix countExceptionsThrown",
   "type": "graph",
   "description": "not in [prom ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fiat:hystrix:countExceptionsThrown)",
     "legendFormat": "countExceptionsThrown"
    }
   ]
  },
  {
   "title": "fiat hystrix rollingCountFailure",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fiat:hystrix:rollingCountFailure)",
     "legendFormat": "rollingCountFailure"
    }
   ]
  },
  {
   "title": "fiat unknown okhttp percentage",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " 100*sum(fiat:okhttp:requests__count_total{status=\"Unknown\",success=\"false\"})/sum(fiat:okhttp:requests__count_total)",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "fiat 2XX okhttp percentage",
   "type": "graph",
   "description": "not in prom ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*sum(fiat:okhttp:requests__count_total{status=\"2xx\",success=\"true\"})/sum(fiat:okhttp:requests__count_total)",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "front50",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "front50 pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-front50-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-front50-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-front50-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "front50 controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(front50:controller:invocations__total[$SamplePeriod])) / sum(rate(front50:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "front50 controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(front50:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "front50 memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "front50:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "front50 controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(front50:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(front50:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "front50 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(front50:controller:invocations__count_total{status=\"5xx\"})/sum(front50:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "front50 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(front50:controller:invocations__count_total{status=\"2xx\"})/sum(front50:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "front50 cache size",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(front50:storageServiceSupport:cacheSize__value) by (objectType)",
       "legendFormat": "{{ objectType }}"
      }
     ]
    }
   ]
  },
  {
   "title": "rosco",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "rosco pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-rosco-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-rosco-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-rosco-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "rosco controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rosco:controller:invocations__total[$SamplePeriod])) / sum(rate(rosco:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "rosco controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(rosco:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "rosco memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "rosco:jvm:memory:used__value", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "rosco controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(rosco:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(rosco:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "rosco 5XX percentage",
     "type": "graph",
     "description": "in prom but no data",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(rosco:controller:invocations__count_total{status=\"5xx\"})/sum(rosco:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "rosco 2XX percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(front50:controller:invocations__count_total{status=\"2xx\"})/sum(front50:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "rosco bakes active",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(rosco:bakesActive__value)", "legendFormat": "bakesActive" }
     ]
    }
   ]
  },
  {
   "title": "echo-scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "echo pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-echo-.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-echo-.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-echo-.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "echo controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "not in  prom ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(echo_scheduler:controller:invocations__total[$SamplePeriod])) / sum(rate(echo_scheduler:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "echo controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(echo_scheduler:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "echo memory used",
     "type": "graph",
     "description": "not in prom",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "echo_scheduler:jvm:memory:used__value",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "echo controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(echo_scheduler:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(echo_scheduler:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "echo 5XX percentge",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(echo_scheduler:controller:invocations__count_total{status=\"5xx\"})/sum(echo_scheduler:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "echo 2XX percentage",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(echo_scheduler:controller:invocations__count_total{status=\"2xx\"})/sum(echo_scheduler:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  },
  {
   "title": "echo-worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "echo-worker pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{pod=~\"spin-echo-worker.*\"} == 1)",
       "legendFormat": "pods up"
      },
      {
       "expr": "count(up{pod=~\"spin-echo-worker.*\"} == 0) OR on() vector(0)",
       "legendFormat": "pods down"
      },
      {
       "expr": "count(up{pod=~\"spin-echo-worker.*\"})",
       "legendFormat": "total pods"
      }
     ]
    },
    {
     "title": "echo-worker controller latency [${SamplePeriod}]",
     "type": "graph",
     "description": "not in  prom ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(echo_worker:controller:invocations__total[$SamplePeriod])) / sum(rate(echo_worker:controller:invocations__count_total[$SamplePeriod]))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "echo-worker controller invocations by method [${SamplePeriod}]",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": " label_replace(sum(rate(echo_worker:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{ controller }} / {{ method }}"
      }
     ]
    },
    {
     "title": "echo-worker memory used",
     "type": "graph",
     "description": "not in prom",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "echo_worker:jvm:memory:used__value",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "echo-worker controller invocation latency by method [${SamplePeriod}]",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(rate(echo_worker:controller:invocations__total[$SamplePeriod])) by (controller, method)  / sum(rate(echo_worker:controller:invocations__count_total[$SamplePeriod])) by (controller, method), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
       "legendFormat": "{{controller}}/{{method}}"
      }
     ]
    },
    {
     "title": "echo-worker 5XX percentge",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(echo_worker:controller:invocations__count_total{status=\"5xx\"})/sum(echo_worker:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "echo-worker 2XX percentage",
     "type": "graph",
     "description": "not in prom ",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*sum(echo_worker:controller:invocations__count_total{status=\"2xx\"})/sum(echo_worker:controller:invocations__count_total)",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  }
 ]
}