global: 
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ksrinimba@gmail.com'
  smtp_auth_username: 'opsmxgcetest@gmail.com'
  smtp_auth_password: 'pcgdyunegqrnppcl'
receivers:
- name: opsmx_alert_receivers
  email_configs:
  - to: no-reply-demo@opsmx.io
  #- to: srinivas@opsmx.io
    send_resolved: true
    text: " \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    send_resolved: true
    title: '{{.CommonAnnotations.summary}}'
    text: '{{ .CommonAnnotations.description }}'
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
- name: opsmx_email_only
  email_configs:
  #- to: srinivas@opsmx.io
  - to: no-reply-demo@opsmx.io
    send_resolved: true
    text: " \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 
route:
  group_interval: 5m # Changed from 5m
  group_wait: 10s
  repeat_interval: 2h # Was set to 3h, changed for testing
  #receiver: opsmx_alert_receivers
  receiver: opsmx_email_only
  routes:
  - match: 
      severity: warning
    #receiver: opsmx_alert_receivers
    receiver: opsmx_email_only
