apiVersion: v1
data:
  alertmanager.yml: "#global: {}\n#receivers:\n#- name: default-receiver\n#route:\n#
    \ group_interval: 5m\n#  group_wait: 10s\n#  receiver: default-receiver\n#  repeat_interval:
    3h\nglobal: \n  smtp_smarthost: 'smtp.gmail.com:587'\n  smtp_from: 'opsmxgcetest@gmail.com'\n
    \ smtp_auth_username: 'opsmxgcetest@gmail.com'\n  smtp_auth_password: 'pcgdyunegqrnppcl'\nreceivers:\n-
    name: opsmx_alert_receivers\n  email_configs:\n  - to: no-reply-demo@opsmx.io\n
    \   send_resolved: true\n    text: \" \\nsummary: {{ .CommonAnnotations.summary
    }}\\ndescription: {{ .CommonAnnotations.description }}\" \n  slack_configs:\n
    \ - api_url: https://hooks.slack.com/services/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\n
    \   icon_url: https://avatars3.githubusercontent.com/u/3380462\n    send_resolved:
    true\n    title: '{{.CommonAnnotations.summary}}'\n    text: '{{ .CommonAnnotations.description
    }}'\n    #title: \"{{ range .Alerts }}{{ .Annotations.summary }}\\n{{ end }}\"\n
    \   #text: \"{{ range .Alerts }}{{ .Annotations.description }}\\n{{ end }}\"\n
    \   #text: \"<!channel> \\nsummary: {{ .CommonAnnotations.summary }}\\ndescription:
    {{ .CommonAnnotations.description }}\" \n- name: opsmx_email_only\n  email_configs:\n
    \ - to: no-reply-demo@opsmx.io\n    send_resolved: true\n    text: \" \\nsummary:
    {{ .CommonAnnotations.summary }}\\ndescription: {{ .CommonAnnotations.description
    }}\" \nroute:\n  group_interval: 5m # Changed from 5m\n  group_wait: 10s\n  repeat_interval:
    2h # Was set to 3h, changed for testing\n  receiver: opsmx_alert_receivers\n  routes:\n
    \ - match: \n      severity: warning\n    receiver: opsmx_alert_receivers\n    #receiver:
    opsmx_email_only\n"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: oes
    meta.helm.sh/release-namespace: oes
  creationTimestamp: "2021-06-18T06:52:53Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.16.2
    component: alertmanager
    heritage: Helm
    release: oes
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
    manager: Go-http-client
    operation: Update
    time: "2021-06-18T06:52:53Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:alertmanager.yml: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-06-24T08:10:18Z"
  name: oes-prometheus-alertmanager
  namespace: oes
  resourceVersion: "2374188"
  selfLink: /api/v1/namespaces/oes/configmaps/oes-prometheus-alertmanager
  uid: f483f163-aa5c-4aa1-9a87-9bcfc5364ca0
